# Inserts new line before shell prompts
add_newline = true

format = """
$directory\
[](fg:#434C5E bg:#4C566A)\
$git_branch\
$git_status\
[](fg:#4C566A bg:#86BBD8)\
$c\
$java\
$rust\
[](fg:#86BBD8 bg:#33658A)\
[](fg:#33658A) \
"""

[directory]
style = "bg:#434C5E"
format = "[ $path ]($style)"
truncation_length = 4 
truncation_symbol = "…/"

[directory.substitutions]
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = "bg:#86BBD8"
detect_extensions = ['c', 'h', 'cpp']
format = '[ $symbol]($style)'

[git_branch]
symbol = ""
style = "bg:#4C566A"
format = '[ $symbol $branch]($style)'

[git_status]
style = "bg:#4C566A"
format = '[ $all_status$ahead_behind]($style)'

[java]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol]($style)'

[time]
disabled = true
